# Generated by Django 6.0.5

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Installation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "installation_id",
                    models.BigIntegerField(
                        help_text="GitHub's installation ID",
                        unique=True,
                    ),
                ),
                (
                    "account_login",
                    models.CharField(
                        help_text="GitHub username or organisation name",
                        max_length=255,
                    ),
                ),
                (
                    "account_type",
                    models.CharField(
                        choices=[("User", "User"), ("Organization", "Organization")],
                        help_text="'User' or 'Organization'",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "remote_deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Set when GitHub confirms the installation no longer exists",
                        null=True,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
