# Generated by Django 6.0.5 on 2026-07-08 06:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("github_app", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="installation",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                help_text="Authenticated user who connected this installation. Their installations (and audits) resolve by ownership across sessions and devices; anonymous funnel installs have no owner and are tracked by session instead.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="installations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
