# Generated by Django 6.0.5

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("github_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "installation",
                    models.ForeignKey(
                        help_text="GitHub App installation that initiated this audit",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="audit_jobs",
                        to="github_app.installation",
                    ),
                ),
                (
                    "repo_full_name",
                    models.CharField(
                        help_text="Full repository name (owner/repo)",
                        max_length=255,
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Email address to send the report to",
                        max_length=254,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("cloning", "Cloning"),
                            ("awaiting_approval", "Awaiting Approval"),
                            ("running", "Running"),
                            ("done", "Done"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        help_text="Current status of the audit job",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "report",
                    models.TextField(
                        blank=True,
                        help_text="Audit report content (empty until job completes)",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
