# Generated by Django 6.0.5 on 2026-05-21 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installation_id', models.BigIntegerField(help_text='GitHub App installation ID (stored for audit trail, even after deletion)')),
                ('installation_deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when the GitHub App installation was deleted (set after cloning)', null=True)),
                ('repo_full_name', models.CharField(help_text='Full repository name (owner/repo)', max_length=255)),
                ('email', models.EmailField(help_text='Email address to send the report to', max_length=254)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('cloning', 'Cloning'), ('awaiting_approval', 'Awaiting Approval'), ('running', 'Running'), ('done', 'Done'), ('failed', 'Failed')], default='pending', help_text='Current status of the audit job', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.TextField(blank=True, help_text='Audit report content (empty until job completes)')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
