# Generated by Django 6.0.5 on 2026-06-11 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditsuite',
            name='report_template',
            field=models.TextField(blank=True, default='', help_text='Custom HTML report template for PDF generation. Leave blank to use the REPORT_TEMPLATE_PATH env var or the bundled default.'),
        ),
    ]
