# Generated by Django 6.0.5 on 2026-07-03 14:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("audit", "0003_shared_agent_library"),
    ]

    operations = [
        migrations.AddField(
            model_name="auditsuite",
            name="max_run_cost_usd",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Optional override for the cumulative estimated dollar budget of a whole run (orchestrator + subagents). Blank/0 falls back to AI_MAX_RUN_COST_USD.",
                max_digits=8,
                null=True,
            ),
        ),
    ]
