# Generated by Django 6.0.5 on 2026-08-03 13:07

from django.db import migrations, models


def mark_existing_reports_sent(apps, schema_editor):
    # Reports for runs that completed before this feature were already emailed.
    AuditRun = apps.get_model("audit", "AuditRun")
    AuditRun.objects.filter(status="completed").update(report_state="sent")


def clear_report_state(apps, schema_editor):
    AuditRun = apps.get_model("audit", "AuditRun")
    AuditRun.objects.update(report_state="")


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0004_auditsuite_max_run_cost_usd'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditrun',
            name='report_state',
            field=models.CharField(blank=True, choices=[('awaiting_approval', 'Awaiting Approval'), ('approved', 'Approved'), ('sending', 'Sending'), ('sent', 'Sent'), ('rejected', 'Rejected')], default='', help_text="Delivery stage of this run's report. Blank until the run completes; a completed report waits at 'awaiting_approval' until a staff member approves or rejects it.", max_length=32),
        ),
        migrations.AddField(
            model_name='auditrun',
            name='sending_since',
            field=models.DateTimeField(blank=True, help_text="Set when a worker claims this report for sending; cleared on any transition out of 'sending'. Used to spot a worker that died mid-send.", null=True),
        ),
        migrations.AddField(
            model_name='auditrun',
            name='approved_at',
            field=models.DateTimeField(blank=True, help_text="Set on a fresh approval (awaiting_approval -> approved); cleared on transitions out of the approval stage, except a failed-send rollback, which preserves it. Used to spot a queued send whose message was lost.", null=True),
        ),
        migrations.RunPython(mark_existing_reports_sent, clear_report_state),
        migrations.AlterField(
            model_name='auditjob',
            name='keep_sources',
            field=models.BooleanField(default=False, help_text='Never auto-delete the cloned sources. Off (default) means the clone is removed once every report on this job has been approved and sent; only staff submitters may opt in to keeping sources.'),
        ),
    ]
