# Generated by Django 6.0.5 on 2026-07-31 12:34

from django.db import migrations, models


def mark_existing_reports_sent(apps, schema_editor):
    # Reports for runs that completed before this feature were already emailed.
    AuditRun = apps.get_model("audit", "AuditRun")
    AuditRun.objects.filter(status="completed").update(report_state="sent")


def clear_report_state(apps, schema_editor):
    AuditRun = apps.get_model("audit", "AuditRun")
    AuditRun.objects.update(report_state="")


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0004_auditsuite_max_run_cost_usd'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditrun',
            name='report_state',
            field=models.CharField(blank=True, choices=[('awaiting_approval', 'Awaiting Approval'), ('approved', 'Approved'), ('sent', 'Sent'), ('rejected', 'Rejected')], default='', help_text="Delivery stage of this run's report. Blank until the run completes; a completed report waits at 'awaiting_approval' until a staff member approves or rejects it.", max_length=32),
        ),
        migrations.RunPython(mark_existing_reports_sent, clear_report_state),
    ]
