# Generated by Django 6.0.5 on 2026-07-31 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0005_auditrun_report_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditjob',
            name='keep_sources',
            field=models.BooleanField(default=False, help_text='Never auto-delete the cloned sources. Off (default) means the clone is removed once every report on this job has been approved and sent; only staff submitters may opt in to keeping sources.'),
        ),
    ]
