# Generated by Django 6.0.5 on 2026-09-25 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0005_report_approval_gate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditsuite',
            name='model',
            field=models.CharField(help_text='Model name from AVAILABLE_AI_MODELS. Combined with AI_MODEL_PROVIDER at run time.', max_length=100),
        ),
    ]
