# Generated by Django 6.0.5 on 2026-08-03 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0006_alter_auditjob_keep_sources'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditrun',
            name='sending_since',
            field=models.DateTimeField(blank=True, help_text="Set when a worker claims this report for sending; cleared on any transition out of 'sending'. Used to spot a worker that died mid-send.", null=True),
        ),
        migrations.AlterField(
            model_name='auditrun',
            name='report_state',
            field=models.CharField(blank=True, choices=[('awaiting_approval', 'Awaiting Approval'), ('approved', 'Approved'), ('sending', 'Sending'), ('sent', 'Sent'), ('rejected', 'Rejected')], default='', help_text="Delivery stage of this run's report. Blank until the run completes; a completed report waits at 'awaiting_approval' until a staff member approves or rejects it.", max_length=32),
        ),
    ]
